[book]
authors = ["Atliac"]
language = "en"
src = "docs"
title = "wgc Tutorial"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/Atliac/wgc"
edit-url-template = "https://github.com/Atliac/wgc/edit/main/docs/{path}"
